[package]
name = "mirage_backend_codegen_llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
mirage_backend_llvm = { path = "../mirage-backend-llvm" }
mirage_backend_output = { path = "../mirage-backend-output" }
mirage_frontend = { path = "../../mirage-frontend" }