[package]
name = "mirage_backend_opti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mirage_frontend = { path = "../../mirage-frontend" }
log = "0.4.20"
